### ISSUE TITLE
How to start gepard on the commandline

### ISSUE THREAD

**Issue by sajvanderzeeuw** [univieCUBE/gepard#1]
Hi,

First of all thanks of making this nice tool. In your .HTML tutorial you distribute with Gepard, i see that you also support an commandline version of Gepard which should be started from a .sh file from the toplevel of the Gepard dir. Can you please tell me where i can find that script. Since when i clone directly from here, i get nothing. As you can see in the tree below. Hope you can help me out. Thanks,

Best regards,

Sander

``````
.
├── dist
│   └── Gepard-1.40.jar
├── Gepard.jardesc
├── LICENSE
├── LICENSE.txt
├── README.md
├── README run without JAR.txt
├── README.txt
├── resources
│   ├── help
│   │   ├── help.xml
│   │   ├── reference.txt
│   │   └── usermsg.txt
│   ├── images
│   │   ├── export.gif
│   │   ├── gepard.gif
│   │   ├── logo.gif
│   │   ├── zoomfull.gif
│   │   ├── zoomin.gif
│   │   └── zoomout.gif
│   ├── matrices
│   │   ├── blosum62.mat
│   │   ├── edna.mat
│   │   ├── ednaorig.mat
│   │   ├── matrices.xml
│   │   ├── pam250.mat
│   │   └── protidentity.mat
│   └── tutorial.html
├── src
│   ├── matrices
│   │   ├── blosum62.mat
│   │   ├── edna.mat
│   │   ├── ednaorig.mat
│   │   ├── matrices.xml
│   │   ├── pam250.mat
│   │   └── protidentity.mat
│   └── org
│       └── gepard
│           ├── client
│           │   ├── AutoParameters.java
│           │   ├── BrowserLauncher.java
│           │   ├── ClientGlobals.java
│           │   ├── cmdline
│           │   │   ├── CommandLineArguments.java
│           │   │   ├── CommandLine.java
│           │   │   └── InvalidArgumentsException.java
│           │   ├── Config.java
│           │   ├── Controller.java
│           │   ├── DotplotInfo.java
│           │   ├── DrawTarget.java
│           │   ├── GeneNames.java
│           │   ├── InvalidParamSetException.java
│           │   ├── Plotter.java
│           │   ├── Start.java
│           │   ├── SubstMatrixFile.java
│           │   ├── SubstMatrixList.java
│           │   └── userinterface
│           │       ├── AboutDialog.java
│           │       ├── ContainerWindow.java
│           │       ├── ControlPanel.java
│           │       ├── CustomComboBox.java
│           │       ├── DrawPanel.java
│           │       ├── ExampleFileFilter.java
│           │       ├── HelpTexts.java
│           │       ├── InfoPanel.java
│           │       ├── MainPanel.java
│           │       ├── ProxyDialog.java
│           │       ├── StatusDialog.java
│           │       ├── UserMessageDialog.java
│           │       └── WindowPos.java
│           └── common
│               ├── AbortionChecker.java
│               ├── Base64.java
│               ├── CompressedDotMatrix.java
│               ├── Compression.java
│               ├── DotMatrixCallback.java
│               ├── DotMatrix.java
│               ├── FASTAReader.java
│               ├── FASTAWriter.java
│               ├── GenSAFile.java
│               ├── GenSAFileVmatch.java
│               ├── InvalidFASTAFileException.java
│               ├── InvalidSubMatFileException.java
│               ├── LEDataInputStream.java
│               ├── LEDataOutputStream.java
│               ├── ParameterSet.java
│               ├── SAXFinishedException.java
│               ├── Sequence.java
│               ├── SubstitutionMatrix.java
│               ├── SuffixArray.java
│               └── VmatchConverter.java
└── tutorial.html

13 directories, 80 files```
``````

**Comment by rattei** [comment]
Hello,

I'd recommend to start start the jar file. Either double click or use java -jar dist/Gepard-140.jar from the command line.

Best,
Thomas

__________________________________________________________________
                                                                   ue
Prof. Dr. Thomas Rattei                                          bbc
CUBE - Division of Computational Systems Biology                cbc
Dept. of Microbiology and Ecosystem Science         ec       cce.cc
University of Vienna                                 bbbc ccuc....b
Althanstrasse 14                                     c  bb........ce
1090 Vienna, Austria                                     ue........cu
Phone  +43 1 4277 76680                                   ce......c bbue
Mobile +43 664 60277 76680                                 e..ccucc   be
e-mail thomas.rattei@univie.ac.at                           bcc
web    cube.univie.ac.at                                  cbb
________________________________________________________ u c

**Comment by sajvanderzeeuw** [comment]
HI Thomas,

Thanks for the quick reply! I know how to start the jar file but that gives me an GUI, i basically need the functionalities directly on the commandline which enables me to run this tool on multiple comparisons at once. I was hoping that the bash script you are talking about in the README, and tutorial in this repository would give me that functionality. 

Best,

Sander

**Comment by rattei** [comment]
Hi Sander,

sorry, the readme.txt file was not up-to-date in that point. For command line functionality please run gepard this way:

java -cp Gepard-1.40.jar org.gepard.client.cmdline.CommandLine

Best,
Thomas

__________________________________________________________________
                                                                   ue
Prof. Dr. Thomas Rattei                                          bbc
CUBE - Division of Computational Systems Biology                cbc
Dept. of Microbiology and Ecosystem Science         ec       cce.cc
University of Vienna                                 bbbc ccuc....b
Althanstrasse 14                                     c  bb........ce
1090 Vienna, Austria                                     ue........cu
Phone  +43 1 4277 76680                                   ce......c bbue
Mobile +43 664 60277 76680                                 e..ccucc   be
e-mail thomas.rattei@univie.ac.at                           bcc
web    cube.univie.ac.at                                  cbb
________________________________________________________ u c

**Comment by sajvanderzeeuw** [comment]
HI Thomas,

Thanks for answering so fast. Would be a nice idea to update the 
tutorial indeed, or just add one small .sh script which runs ```java -cp 
Gepard-1.40.jar org.gepard.client.cmdline.CommandLine```.

Best and again thanks!

Sander

**Comment by splaisan** [comment]
I have similar issues as above. I want to run many plots and would prefer cli.
my command below does not complain and no output is created
do I need to specify all parameters or are some set by default?
the -word and -window were defined from a good GUI run
Thanks for your help

```
java -cp /opt/biotools/gepard/gepard.jar org.gepard.client.cmdline.CommandLine -seq1 "ref1.fasta" -seq2 "ref2.fasta" -word 100 -window 1000 -outfile "gepard_ref1_vs_ref2.png"

Gepard 1.40 final - command line mode

Reference:
Krumsiek J, Arnold R, Rattei T
Gepard: A rapid and sensitive tool for creating dotplots on genome scale.
Bioinformatics 2007; 23(8): 1026-8. PMID: 17309896

Parameters are supplied as -name value

Required parameters:
  -seq1:        first sequence file
  -seq2:        second sequence file
  -matrix:      substitution matrix file
  -outfile:     output file name

Dotplot image parameters:
  -maxwidth:    maximum width of the generated image (default: 750)
  -maxheight:   maximum height of the generated image (default: 750)
  -zoom:        specify a zoom factor for the dotplot
  note: you can only use maxwidth/maxheight OR zoom
        when using maxwidth/maxheight the program tries to generate the largest
        possible dotplot within the given bounds
  -format:      output format, one of:  'png', 'jpg', 'bmp' (default:PNG)

Dotplot computation parameters:
  -secondcomp   use complementary of second sequence
  -word:        word length for suffix array mode (default: 10)
  -window:      window size for ordinary dotplot mode (default: 0)
  if a window value and no word value is specified, word=0 is assumed

Suffix array parameters:
  -safile       load suffix array from file instead of calculating it
  -sasecondseq  the suffix array is for the second sequence
  if -sasecondseq is NOT specified, the suffix array will be used for first sequence

Coordinate parameters (absolute values of % values)
  -from1,-to1   coordinates of first sequence
  -from2,-to2   coordinates of second sequence
  if these parameters are not specified the full sequence will be used

Display parameters:
  -lower        lower limit for dot intensity (in %)
  -upper        upper limit for dot intensity (in %)
  -greyscale    greyscale start value (in %)

Miscellaneous:
  -silent       generate no output (except error messages)
```
all tried commands execute like this even only specifying seq1 and seq2

**Comment by rattei** [comment]
Hello Stephane,

you did not provide the -matrix parameter, which is mandatory. If you add it, like in this test, it works:

java -cp /apps/gepard/1.40/dist/Gepard-1.40.jar org.gepard.client.cmdline.CommandLine -seq1 ref1.fasta -seq2 ref2.fasta -matrix /apps/gepard/1.40/resources/matrices/edna.mat -word 100 -window 1000 -outfile gepard_ref1_vs_ref2.png

Best,
Thomas

__________________________________________________________________
                                                                   ue
Prof. Dr. Thomas Rattei                                          bbc
CUBE - Division of Computational Systems Biology                cbc
Dept. of Microbiology and Ecosystem Science         ec       cce.cc
University of Vienna                                 bbbc ccuc....b
Althanstrasse 14                                     c  bb........ce
1090 Vienna, Austria                                     ue........cu
Phone  +43 1 4277 76680                                   ce......c bbue
Mobile +43 664 60277 76680                                 e..ccucc   be
e-mail thomas.rattei@univie.ac.at                           bcc
web    cube.univie.ac.at                                  cbb
________________________________________________________ u c

**Comment by splaisan** [comment]
Thanks a lot Thomas,

I corrected my comment after finding out I was missing the matrix indeed.
I have it now working, the problem was that I downloaded only the jar and did not have the matrices folder with it.
I now copied it from the src folder and link to the edna.mat in my cmd
great tool!!

Best
Stephane


Stéphane Plaisance – Staff Scientist | Bioinformatician
VIB Nucleomics Core 
Herestraat 49 – Post Box 816 – 3000 Leuven – Belgium 
O&N4 Building – 8th Floor – Room 08.440 
Tel. +32 16 37 31 26 
Lync. +32 16 32 00 60 
www.nucleomics.be <http://www.nucleomics.be/> <http://www.nucleomics.be/> <http://www.nucleomics.be/> <http://www.nucleomics.be/>  <http://www.vib.be/>

**Comment by rattei** [comment]
Hello Stephane,

these are no special matrices, you might just use them e.g. from a commandline blast installation.

best,
Thomas

> Am 21.04.2017 um 13:36 schrieb Stephane Plaisance <notifications@github.com>:
> 
> Thanks a lot Thomas,
> 
> I corrected my comment after finding out I was missing the matrix indeed.
> I have it now working, the problem was that I downloaded only the jar and did not have the matrices folder with it.
> I now copied it from the src folder and link to the edna.mat in my cmd
> great tool!!
> 
> Best
> Stephane
> 
> 
> Stéphane Plaisance – Staff Scientist | Bioinformatician
> VIB Nucleomics Core 
> Herestraat 49 – Post Box 816 – 3000 Leuven – Belgium 
> O&N4 Building – 8th Floor – Room 08.440 
> Tel. +32 16 37 31 26 
> Lync. +32 16 32 00 60 
> www.nucleomics.be <http://www.nucleomics.be/> <http://www.nucleomics.be/> <http://www.nucleomics.be/> <http://www.nucleomics.be/> <http://www.vib.be/>

**Comment by DominikDitoIvosevic** [comment]
Would it be possible to start gepard from command line with parameters to the 2 fasta files which need comparison? Are there instructions for the command line parameters if there are any?

**Comment by rattei** [comment]
Hello,

When you run the gepard application from the command line, as explained in the readme.txt, it shows the usage:

java -cp dist/Gepard-1.40.jar org.gepard.client.cmdline.CommandLine

Gepard 1.40 final - command line mode

Reference:
Krumsiek J, Arnold R, Rattei T
Gepard: A rapid and sensitive tool for creating dotplots on genome scale.
Bioinformatics 2007; 23(8): 1026-8. PMID: 17309896

Parameters are supplied as -name value

Required parameters:
  -seq1:        first sequence file
  -seq2:        second sequence file
  -matrix:      substitution matrix file
  -outfile:     output file name

Dotplot image parameters:
  -maxwidth:    maximum width of the generated image (default: 750)
  -maxheight:   maximum height of the generated image (default: 750)
  -zoom:        specify a zoom factor for the dotplot
  note: you can only use maxwidth/maxheight OR zoom
        when using maxwidth/maxheight the program tries to generate the largest
        possible dotplot within the given bounds
  -format:      output format, one of:  'png', 'jpg', 'bmp' (default:PNG)

Dotplot computation parameters:
  -secondcomp   use complementary of second sequence
  -word:        word length for suffix array mode (default: 10)
  -window:      window size for ordinary dotplot mode (default: 0)
  if a window value and no word value is specified, word=0 is assumed

Suffix array parameters:
  -safile       load suffix array from file instead of calculating it
  -sasecondseq  the suffix array is for the second sequence
  if -sasecondseq is NOT specified, the suffix array will be used for first sequence

Coordinate parameters (absolute values of % values)
  -from1,-to1   coordinates of first sequence
  -from2,-to2   coordinates of second sequence
  if these parameters are not specified the full sequence will be used

Display parameters:
  -lower        lower limit for dot intensity (in %)
  -upper        upper limit for dot intensity (in %)
  -greyscale    greyscale start value (in %)

Miscellaneous:
  -silent       generate no output (except error messages)


Best regards,
Thomas Rattei
________________________________________________________
Prof. Dr. Thomas Rattei
CUBE - Division of Computational Systems Biology
Dept. of Microbiology and Ecosystem Science
University of Vienna
Althanstrasse 14
1090 Vienna, Austria
Phone  +43 1 4277 91280
Mobile +43 664 60277 91280
e-mail thomas.rattei@univie.ac.at<mailto:thomas.rattei@univie.ac.at>
web    cube.univie.ac.at
________________________________________________________

On 23.01.2020, at 19:11, Dominik Ivosevic <notifications@github.com<mailto:notifications@github.com>> wrote:


Would it be possible to start gepard from command line with parameters to the 2 fasta files which need comparison? Are there instructions for the command line parameters if there are any?
